In [14]:
import numpy as np

In [15]:
######################################################
######################################################
# Code to aid in computing intersection products in Hilb_3 P^3.
# Meant to pair with "On the nef and effective cones of Hilbert schemes of points in projective space"
# by Gwyneth Moreland
# I would like to give my thanks to Serina Hu for assisting with this code.
# Code last updated: Jan 3, 2023
######################################################
######################################################
######################################################
# Please note: this code is intended to be paired with the Mathematica code 
# available at gwynethmoreland.github.io
######################################################
######################################################


######################################################
######################################################
# First: matrix of all weight 9 monomials and their corresponding numerical value
# Information is stored as follows: [P, H, P_3, \beta, P_2, l, p, NUM VALUE].
# organized by total P,H degree.
######################################################
######################################################
# To start: degree 0 in P,H     (Tables 1,2)
######################################################
######################################################
# Lastly, note that four of these entries differ from Tables 1-10 in
# Rossello-Llompart's 1990 paper "The Chow ring of Hilb^3 P^3". 
# This is error correcting. Computations are given in my paper.
######################################################
M = [
    [0,0,3,0,0,0,0,0],
    [0,0,2,1,0,0,0,0],
    [0,0,1,2,0,0,0,1],
    [0,0,0,3,0,0,0,4],
    ############
    ############
    ############
    [0,0,1,0,3,0,0,0],
    [0,0,1,0,2,1,0,0],
    [0,0,1,0,2,0,1,0],
    [0,0,1,0,1,2,0,0],
    [0,0,1,0,1,1,1,0],
    [0,0,1,0,1,0,2,0],
    [0,0,1,0,0,3,0,1],
    [0,0,1,0,0,2,1,0],
    [0,0,1,0,0,1,2,0],
    [0,0,1,0,0,0,3,1],
    ############
    [0,0,0,1,3,0,0,0],
    [0,0,0,1,2,1,0,0],
    [0,0,0,1,2,0,1,0],
    [0,0,0,1,1,2,0,0],
    [0,0,0,1,1,1,1,1],
    [0,0,0,1,1,0,2,1],
    [0,0,0,1,0,3,0,3],
    [0,0,0,1,0,2,1,0],
    [0,0,0,1,0,1,2,1],
    [0,0,0,1,0,0,3,3],
######################################################
######################################################
######################################################
####   degree 1 in P,H      (Table 3)
######################################################
######################################################
######################################################
    [0,1,0,0,4,0,0,2],
    [0,1,0,0,3,1,0,-2],
    [0,1,0,0,3,0,1,0],
    [0,1,0,0,2,2,0,2],
    [0,1,0,0,2,1,1,0],
    [0,1,0,0,2,0,2,0],
    [0,1,0,0,1,3,0,3],
    [0,1,0,0,1,2,1,2],
    [0,1,0,0,1,1,2,2],
    [0,1,0,0,1,0,3,3],
    ############
    [1,0,0,0,4,0,0,-2],#TYPO4: by my comp: -2. By table in paper: 2. Fixes (P_2)^3 = 5(P_3)^2-2P_3 P_2 H  formula
    [1,0,0,0,3,1,0,2], #TYPO3: by my comp: 2. By table in paper: -2. Fixes (P_2)^3P\ell formula, O_4max*P_2*P*\ell comp
    [1,0,0,0,3,0,1,0],
    [1,0,0,0,2,2,0,-2],
    [1,0,0,0,2,1,1,0],
    [1,0,0,0,2,0,2,0],
    [1,0,0,0,1,3,0,3],
    [1,0,0,0,1,2,1,0],
    [1,0,0,0,1,1,2,0],
    [1,0,0,0,1,0,3,1],
    ############
    ############
    ############
    [0,1,0,0,0,4,0,0],
    [0,1,0,0,0,3,1,3],
    [0,1,0,0,0,2,2,2],
    [0,1,0,0,0,1,3,3],
    [0,1,0,0,0,0,4,6],
    [0,1,2,0,1,0,0,0],
    [0,1,2,0,0,1,0,0],
    [0,1,2,0,0,0,1,0],
    ############
    [1,0,0,0,0,4,0,0],
    [1,0,0,0,0,3,1,3],
    [1,0,0,0,0,2,2,2],
    [1,0,0,0,0,1,3,0],
    [1,0,0,0,0,0,4,6],
    [1,0,2,0,1,0,0,0],
    [1,0,2,0,0,1,0,0],
    [1,0,2,0,0,0,1,0],
    ############
    ############
    ############
    [0,1,1,1,1,0,0,0],
    [0,1,1,1,0,1,0,0],
    [0,1,1,1,0,0,1,1],
    [0,1,0,2,1,0,0,3],
    [0,1,0,2,0,1,0,3],
    [0,1,0,2,0,0,1,4],
    ############
    [1,0,1,1,1,0,0,0],
    [1,0,1,1,0,1,0,0],
    [1,0,1,1,0,0,1,0],
    [1,0,0,2,1,0,0,1],
    [1,0,0,2,0,1,0,0],
    [1,0,0,2,0,0,1,3],
######################################################
######################################################
######################################################
####   degree 2 in P,H    (Table 4)
######################################################
######################################################
######################################################
    [0,2,1,0,2,0,0,-1],
    [0,2,1,0,1,1,0,1],
    [0,2,1,0,1,0,1,0],
    [0,2,1,0,0,2,0,1],
    [0,2,1,0,0,1,1,1],
    [0,2,1,0,0,0,2,2],
    ############
    [1,1,1,0,2,0,0,1],
    [1,1,1,0,1,1,0,-1],
    [1,1,1,0,1,0,1,0],
    [1,1,1,0,0,2,0,1],
    [1,1,1,0,0,1,1,0],
    [1,1,1,0,0,0,2,0],
    ############
    [2,0,1,0,2,0,0,-1],
    [2,0,1,0,1,1,0,1],
    [2,0,1,0,1,0,1,0],
    [2,0,1,0,0,2,0,-1],
    [2,0,1,0,0,1,1,0],
    [2,0,1,0,0,0,2,0],
    ############
    ############
    ############
    [0,2,0,1,2,0,0,1],
    [0,2,0,1,1,1,0,3],
    [0,2,0,1,1,0,1,5],
    [0,2,0,1,0,2,0,3],
    [0,2,0,1,0,1,1,3],
    [0,2,0,1,0,0,2,7],
    ############
    [1,1,0,1,2,0,0,-1],
    [1,1,0,1,1,1,0,1],
    [1,1,0,1,1,0,1,1],
    [1,1,0,1,0,2,0,3],
    [1,1,0,1,0,1,1,2],
    [1,1,0,1,0,0,2,5],
    ############
    [2,0,0,1,2,0,0,1],
    [2,0,0,1,1,1,0,-1], #Originally thought there was an error, but this is fine
    [2,0,0,1,1,0,1,0],
    [2,0,0,1,0,2,0,1],
    [2,0,0,1,0,1,1,1],
    [2,0,0,1,0,0,2,1],
######################################################
######################################################
######################################################
####   degree 3 in P,H    (Table 5)
######################################################
######################################################
######################################################
    [0,3,2,0,0,0,0,1],
    [0,3,1,1,0,0,0,3],
    [0,3,0,2,0,0,0,9],
    [0,3,0,0,3,0,0,-7],
    [0,3,0,0,2,1,0,9],
    [0,3,0,0,2,0,1,3],
    [0,3,0,0,1,2,0,7],
    ############
    [1,2,2,0,0,0,0,-1],
    [1,2,1,1,0,0,0,1],
    [1,2,0,2,0,0,0,7],
    [1,2,0,0,3,0,0,1],
    [1,2,0,0,2,1,0,-3],
    [1,2,0,0,2,0,1,-3], #TYPO1: by my comp: -3. By paper: 3. Fixes 3P_3*P = (P^2-P_2)P formula.
    [1,2,0,0,1,2,0,7],
    ############
    [2,1,2,0,0,0,0,1],
    [2,1,1,1,0,0,0,-1],
    [2,1,0,2,0,0,0,4],
    [2,1,0,0,3,0,0,5],
    [2,1,0,0,2,1,0,-3],
    [2,1,0,0,2,0,1,3],
    [2,1,0,0,1,2,0,1],
    ############
    [3,0,2,0,0,0,0,-1],
    [3,0,1,1,0,0,0,1],
    [3,0,0,2,0,0,0,0],
    [3,0,0,0,3,0,0,-11],
    [3,0,0,0,2,1,0,9],
    [3,0,0,0,2,0,1,-3],
    [3,0,0,0,1,2,0,-7],
    ############
    ############
    ############
    [0,3,0,0,1,1,1,9],
    [0,3,0,0,1,0,2,12],
    [0,3,0,0,0,3,0,6],
    [0,3,0,0,0,2,1,7],
    [0,3,0,0,0,1,2,9],
    [0,3,0,0,0,0,3,15],
    ############
    [1,2,0,0,1,1,1,4],
    [1,2,0,0,1,0,2,2],
    [1,2,0,0,0,3,0,6],
    [1,2,0,0,0,2,1,7],
    [1,2,0,0,0,1,2,7],
    [1,2,0,0,0,0,3,12],
    ############
    [2,1,0,0,1,1,1,-3],
    [2,1,0,0,1,0,2,0],
    [2,1,0,0,0,3,0,6],
    [2,1,0,0,0,2,1,5],
    [2,1,0,0,0,1,2,2],
    [2,1,0,0,0,0,3,3],
    ############
    [3,0,0,0,1,1,1,3],
    [3,0,0,0,1,0,2,0],
    [3,0,0,0,0,3,0,6],
    [3,0,0,0,0,2,1,-3],
    [3,0,0,0,0,1,2,0],
    [3,0,0,0,0,0,3,1], #TYPO2: by P^3 formula in paper equals 1. In table: -11
######################################################
######################################################
######################################################
####   degree 4 in P,H    (Table 6)
######################################################
######################################################
######################################################
    [0,4,1,0,1,0,0,6],
    [1,3,1,0,1,0,0,-3],
    [2,2,1,0,1,0,0,0],
    [3,1,1,0,1,0,0,3],
    [4,0,1,0,1,0,0,-6],
    ############
    [0,4,1,0,0,1,0,3],
    [1,3,1,0,0,1,0,3],
    [2,2,1,0,0,1,0,0],
    [3,1,1,0,0,1,0,-3],
    [4,0,1,0,0,1,0,6],
    ############
    [0,4,1,0,0,0,1,6],
    [1,3,1,0,0,0,1,3],
    [2,2,1,0,0,0,1,-3],
    [3,1,1,0,0,0,1,3],
    [4,0,1,0,0,0,1,-3],
    ############
    [0,4,0,1,1,0,0,18],
    [1,3,0,1,1,0,0,9],
    [2,2,0,1,1,0,0,-2],
    [3,1,0,1,1,0,0,-1],
    [4,0,0,1,1,0,0,4],
    ############
    [0,4,0,1,0,1,0,9],
    [1,3,0,1,0,1,0,9],
    [2,2,0,1,0,1,0,6],
    [3,1,0,1,0,1,0,1],
    [4,0,0,1,0,1,0,-4],
    ############
    [0,4,0,1,0,0,1,18],
    [1,3,0,1,0,0,1,15], #Careful! But it is correct
    [2,2,0,1,0,0,1,8],
    [3,1,0,1,0,0,1,-2],
    [4,0,0,1,0,0,1,3],
######################################################
######################################################
######################################################
####   degree 5 in P,H    (Table 7)
######################################################
######################################################
######################################################
    [0,5,0,0,2,0,0,40],
    [1,4,0,0,2,0,0,-4],
    [2,3,0,0,2,0,0,-14],
    [3,2,0,0,2,0,0,14],
    [4,1,0,0,2,0,0,4],
    [5,0,0,0,2,0,0,-40],
    ############
    [0,5,0,0,1,1,0,25],
    [1,4,0,0,1,1,0,25],
    [2,3,0,0,1,1,0,8],
    [3,2,0,0,1,1,0,-14],
    [4,1,0,0,1,1,0,2],
    [5,0,0,0,1,1,0,28],
    ############
    [0,5,0,0,1,0,1,40],
    [1,4,0,0,1,0,1,24],
    [2,3,0,0,1,0,1,-6],
    [3,2,0,0,1,0,1,-3],
    [4,1,0,0,1,0,1,12],
    [5,0,0,0,1,0,1,-21],
    ############
    [0,5,0,0,0,2,0,20],
    [1,4,0,0,0,2,0,20],
    [2,3,0,0,0,2,0,20],
    [3,2,0,0,0,2,0,12],
    [4,1,0,0,0,2,0,-4],
    [5,0,0,0,0,2,0,-20],
    ############
    [0,5,0,0,0,1,1,25],
    [1,4,0,0,0,1,1,25],
    [2,3,0,0,0,1,1,18],
    [3,2,0,0,0,1,1,4],
    [4,1,0,0,0,1,1,-12],
    [5,0,0,0,0,1,1,21],
    ############
    [0,5,0,0,0,0,2,40],
    [1,4,0,0,0,0,2,36],
    [2,3,0,0,0,0,2,21],
    [3,2,0,0,0,0,2,-7],
    [4,1,0,0,0,0,2,9],
    [5,0,0,0,0,0,2,-9],
######################################################
#####################################################
######################################################
####   degree 6 in P,H    (Table 8)
######################################################
######################################################
######################################################
    [0,6,1,0,0,0,0,15],
    [1,5,1,0,0,0,0,15],
    [2,4,1,0,0,0,0,3],
    [3,3,1,0,0,0,0,-12],
    [4,2,1,0,0,0,0,12],
    [5,1,1,0,0,0,0,-3],
    [6,0,1,0,0,0,0,-15],
    ############
    [0,6,0,1,0,0,0,45],
    [1,5,0,1,0,0,0,45],
    [2,4,0,1,0,0,0,33],
    [3,3,0,1,0,0,0,12],
    [4,2,0,1,0,0,0,-14],
    [5,1,0,1,0,0,0,11],
    [6,0,0,1,0,0,0,1],
######################################################
#####################################################
######################################################
####   degree 7 in P,H    (Table 9)
######################################################
######################################################
######################################################
    [0,7,0,0,1,0,0,105],
    [1,6,0,0,1,0,0,105],
    [2,5,0,0,1,0,0,45],
    [3,4,0,0,1,0,0,-39],
    [4,3,0,0,1,0,0,-12],
    [5,2,0,0,1,0,0,54],
    [6,1,0,0,1,0,0,-33],
    [7,0,0,0,1,0,0,-105],
    ############
    [0,7,0,0,0,1,0,70],
    [1,6,0,0,0,1,0,70],
    [2,5,0,0,0,1,0,70],
    [3,4,0,0,0,1,0,46],
    [4,3,0,0,0,1,0,2],
    [5,2,0,0,0,1,0,-50],
    [6,1,0,0,0,1,0,53],
    [7,0,0,0,0,1,0,43],
    ############
    [0,7,0,0,0,0,1,105],
    [1,6,0,0,0,0,1,105],
    [2,5,0,0,0,0,1,85],
    [3,4,0,0,0,0,1,33],
    [4,3,0,0,0,0,1,-42],
    [5,2,0,0,0,0,1,33],
    [6,1,0,0,0,0,1,3],
    [7,0,0,0,0,0,1,-66],
######################################################
#####################################################
######################################################
####   degree 9 in P,H    (Table 10)
######################################################
######################################################
######################################################
    [0,9,0,0,0,0,0,280],
    [1,8,0,0,0,0,0,280],
    [2,7,0,0,0,0,0,280],
    [3,6,0,0,0,0,0,200],
    [4,5,0,0,0,0,0,40],
    [5,4,0,0,0,0,0,-160],
    [6,3,0,0,0,0,0,109],
    [7,2,0,0,0,0,0,59],
    [8,1,0,0,0,0,0,-128],
    [9,0,0,0,0,0,0,-280]
    ]

In [16]:
######################################################
######################################################
# The matrix B keeps track of which monomials are in the RL basis.
######################################################
######################################################
B = []

# 0 degree (dim 9 cycle)
B.append([
    [[0,0,0,0,0,0,0]]
])

# 1 degree (dim 8 cycle)
B.append([
    [[1,0,0,0,0,0,0]],
    [[0,1,0,0,0,0,0]]
])

# 2 degree (dim 7 cycle)
B.append([
    [[0,0,0,0,1,0,0]],
    [[2,0,0,0,0,0,0]],
    [[1,1,0,0,0,0,0]],
    [[0,2,0,0,0,0,0]],
    [[0,0,0,0,0,1,0]],
    [[0,0,0,0,0,0,1]]
])

# 3 degree (dim 6 cycle)
B.append([
    [[0,0,1,0,0,0,0]],
    [[1,0,0,0,1,0,0]],
    [[0,1,0,0,1,0,0]],
    [[1,2,0,0,0,0,0]],
    [[2,1,0,0,0,0,0]],
    [[1,0,0,0,0,1,0]],
    [[1,0,0,0,0,0,1]],
    [[0,3,0,0,0,0,0]],
    [[0,1,0,0,0,1,0]],
    [[0,0,0,1,0,0,0]]
])

# 4 degree (dim 5 cycle)
B.append([
    [[1,0,1,0,0,0,0]],
    [[0,1,1,0,0,0,0]],
    [[0,2,0,0,1,0,0]],
    [[1,1,0,0,1,0,0]],
    [[0,0,0,0,1,1,0]],
    [[0,0,0,0,2,0,0]],
    [[0,0,0,0,1,0,1]],
    [[2,2,0,0,0,0,0],[1,3,0,0,0,0,0]],
    [[1,1,0,0,0,1,0]],
    [[1,0,0,1,0,0,0]],
    [[0,2,0,0,0,1,0]],
    [[0,0,0,0,0,2,0]],
    [[0,0,0,0,0,1,1]]
])

# 5 degree (dim 4 cycle)
B.append([
    [[1,1,1,0,0,0,0]],
    [[0,2,1,0,0,0,0]],
    [[0,0,1,0,0,1,0]],
    [[0,0,1,0,1,0,0]],
    [[0,0,1,0,0,0,1]],
    [[0,1,0,0,1,1,0]],
    [[0,1,0,0,2,0,0]],
    [[0,0,0,1,1,0,0]],
    [[0,3,0,0,1,0,0]],
    [[1,2,0,0,1,0,0]],
    [[1,2,0,0,0,1,0]],
    [[1,0,0,0,0,2,0]],
    [[0,1,0,0,0,1,1]]
])

# 6 degree (dim 3 cycle)
B.append([
    [[0,1,1,0,0,1,0]],
    [[0,1,1,0,1,0,0]],
    [[0,0,2,0,0,0,0]],
    [[0,0,1,1,0,0,0]],
    [[0,3,1,0,0,0,0]],
    [[1,2,1,0,0,0,0]],
    [[0,2,0,0,2,0,0],[0,2,0,0,1,1,0]],
    [[0,0,0,0,1,1,1]],
    [[0,0,0,0,1,2,0]],
    [[1,1,0,0,0,1,1]]
])

# 7 degree (dim 2 cycle)
B.append([
    [[0,2,1,0,0,1,0]],
    [[0,2,1,0,1,0,0]],
    [[0,0,1,0,0,2,0]],
    [[0,0,1,0,0,1,1]],
    [[0,0,1,0,1,1,0]],
    [[0,1,0,0,1,1,1]]
])

# 8 degree (dim 1 cycle)
B.append([
    [[0,1,1,0,0,1,1]],
    [[0,1,1,0,0,2,0]]
])

# 9 degree (dim 0 cycle)
B.append([
    [[0,0,1,0,0,3,0]]
])


In [17]:
def degree(b):
    assert len(b) >= 7
    return b[0] + b[1] + 3 * b[2] + 3 * b[3] + 2 * b[4] + 2 * b[5] + 2 * b[6]

def assert_valid(m):
    for i in m:
        assert len(i) == 8
        assert degree(i) == 9

def find_matching_entry(m, vb):
    for e in m:
        if (e[:7] == vb):
            return e
    print("No matching entry for", vb)
    assert False

######################################################
######################################################
# intersection_product takes in a table of intersection products, a basis, and a monomial. It computes
# the intersection products between the monomial and the basis elements of complementary degree.
# the output is an array
######################################################
######################################################
def intersection_product(m, B, b):
    l = []
    d = degree(b)
    for v in B[9 - d]:
        e8 = 0
        for v_part in v:
            vb = (np.array(v_part) + np.array(b)).tolist()
            e = find_matching_entry(m, vb)
            e8 += e[7]
        l.append(e8)
    return np.asarray(l)

assert_valid(M)

In [29]:
def mult_product(A,B):
    l = []
    assert len(A) == len(B)
    assert len(A[0]) == len(A[0])
    for e in A:
        for f in B:
            l.append([np.array(e[0])+np.array(f[0]),e[1]*f[1]])
    return np.asarray(l)

In [30]:
# Some test runs. 
# First line checks that find_matching_entry is grabbing the array attached to a weight 9 monomial
# Second line checks that intersection_product computes all the intersection products of a weight k monomial with
# The basis elements of weight 9-k
print(find_matching_entry(M, [7, 0, 0, 0, 0, 0, 1]))
print(intersection_product(M, B, [2, 0, 0, 0, 0, 0, 1]))

[7, 0, 0, 0, 0, 0, 1, -66]
[ 3 -3  0  0  0 -3  3  0 -6 -3  4 -3  2]


In [31]:
# The monomials appearing in the express of O_{4,max}. Not simplified so as to account for human error
# This is obtained by O_{4,max} = 
maxm = np.asarray([[2,0,0,0,1,0,0],
      [1,1,0,0,1,0,0],
      [0,2,0,0,1,0,0],
      [0,0,0,0,1,0,1],
      [0,0,0,0,2,0,0],
      ################
       [3,1,0,0,0,0,0],
       [2,2,0,0,0,0,0],
       [1,3,0,0,0,0,0],
       [1,1,0,0,0,0,1],
       [1,1,0,0,1,0,0],
       ###############
       [2,0,0,0,0,0,1],
       [1,1,0,0,0,0,1],
       [0,2,0,0,0,0,1],
       [0,0,0,0,0,0,2],
       [0,0,0,0,1,0,1],
       ################
       [2,0,0,0,0,1,0],
       [1,1,0,0,0,1,0],
       [0,2,0,0,0,1,0],
       [0,0,0,0,0,1,1],
       [0,0,0,0,1,1,0]
      ])
# An array keeping track of the coefficients of each weight 4 monomial appearing in the expression of O_{4,max}
maxc = np.asarray([-2,-1,1,-3,9,2,1,-1,3,-9,-2,-1,1,-3,9,-2,-1,1,-3,9])

In [32]:
# Some tests to check that the array was created correctly.
print(maxm[0])
print(maxm[19])

[2 0 0 0 1 0 0]
[0 0 0 0 1 1 0]


In [33]:
# Checking some intersection products for O_{4,max}
# The 1 is interesting, but all the intersection numbers that contribute to that computation have been checked.
l = [0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,20):
    l += maxc[i]*intersection_product(M,B,maxm[i])
print(l)

[ 0  9  3  0  0  9  0  1 27  9  0  0  0]


In [34]:
# monomials appearing in maximal ideals contained in a plane
# coefficients kept track of by maxc
maxm_plane = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,20):
    maxm_plane[i] = maxm[i] + np.array([0,0,1,0,0,0,0])
print(np.asarray(maxm_plane))

[[2 0 1 0 1 0 0]
 [1 1 1 0 1 0 0]
 [0 2 1 0 1 0 0]
 [0 0 1 0 1 0 1]
 [0 0 1 0 2 0 0]
 [3 1 1 0 0 0 0]
 [2 2 1 0 0 0 0]
 [1 3 1 0 0 0 0]
 [1 1 1 0 0 0 1]
 [1 1 1 0 1 0 0]
 [2 0 1 0 0 0 1]
 [1 1 1 0 0 0 1]
 [0 2 1 0 0 0 1]
 [0 0 1 0 0 0 2]
 [0 0 1 0 1 0 1]
 [2 0 1 0 0 1 0]
 [1 1 1 0 0 1 0]
 [0 2 1 0 0 1 0]
 [0 0 1 0 0 1 1]
 [0 0 1 0 1 1 0]]


In [35]:
# testing for intersection products with RL basis and (maximal ideals contained in a plane)
# i.e. computed intersection numbers with B and X_{2,1}
l2 = np.array([0,0,0,0,0,0])
for i in range(0,20):
    l2 += maxc[i]*intersection_product(M,B,maxm_plane[i])
print(l2)

[0 0 0 9 3 0]


In [36]:
# monomials appearing in (maximal ideals contained coplanar with a point and incident to a line).
# i.e. monomials appearing in an expression for O_{4,max}*P*l.
# coefficients still tracked by maxc
maxm_Pl = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,20):
    maxm_Pl[i] = maxm[i] + np.array([1,0,0,0,0,1,0])
print(np.asarray(maxm_Pl))

[[3 0 0 0 1 1 0]
 [2 1 0 0 1 1 0]
 [1 2 0 0 1 1 0]
 [1 0 0 0 1 1 1]
 [1 0 0 0 2 1 0]
 [4 1 0 0 0 1 0]
 [3 2 0 0 0 1 0]
 [2 3 0 0 0 1 0]
 [2 1 0 0 0 1 1]
 [2 1 0 0 1 1 0]
 [3 0 0 0 0 1 1]
 [2 1 0 0 0 1 1]
 [1 2 0 0 0 1 1]
 [1 0 0 0 0 1 2]
 [1 0 0 0 1 1 1]
 [3 0 0 0 0 2 0]
 [2 1 0 0 0 2 0]
 [1 2 0 0 0 2 0]
 [1 0 0 0 0 2 1]
 [1 0 0 0 1 2 0]]


In [37]:
# scrap work. printing some monomials for checking in the RL table.
for i in range(0,20):
    print(maxm[i] + np.array([1,0,0,0,1,1,0]))

[3 0 0 0 2 1 0]
[2 1 0 0 2 1 0]
[1 2 0 0 2 1 0]
[1 0 0 0 2 1 1]
[1 0 0 0 3 1 0]
[4 1 0 0 1 1 0]
[3 2 0 0 1 1 0]
[2 3 0 0 1 1 0]
[2 1 0 0 1 1 1]
[2 1 0 0 2 1 0]
[3 0 0 0 1 1 1]
[2 1 0 0 1 1 1]
[1 2 0 0 1 1 1]
[1 0 0 0 1 1 2]
[1 0 0 0 2 1 1]
[3 0 0 0 1 2 0]
[2 1 0 0 1 2 0]
[1 2 0 0 1 2 0]
[1 0 0 0 1 2 1]
[1 0 0 0 2 2 0]


In [38]:
# checking intersection products for maxm_Pl.
# these products make intuitive sense.
l3 = np.array([0,0,0,0,0,0])
for i in range(0,20):
    l3 += maxc[i]*intersection_product(M,B,maxm_Pl[i])
print(l3)

[3 3 9 0 0 3]


In [39]:
# checking intermediate steps for above.
l = [0,0,0,0,0,0]
for i in range(0,20):
    l += (maxc[i]*intersection_product(M,B,maxm_Pl[i]))
    print(l)
print(l)

[-18 -56  -4  28  14  -6]
[-15 -58  10  20  13  -3]
[-18 -72  18  45  20   1]
[-18 -81  27  33  20   1]
[0 0 0 6 2 1]
[   4  106 -100   10   -6  -23]
[-10  56 -98  56   6 -19]
[ -18   54 -144  -14  -14  -37]
[ -27   18 -132   40    1  -31]
[  0   0  -6 -32  -8  -4]
[ -6 -42  18 -40  -2  -4]
[ -3 -30  14 -58  -7  -6]
[  1 -26  32 -33   0   1]
[  1 -26  26 -54  -6   1]
[  1   1  -1 -18  -6   1]
[ 15  41   7 -42 -18   7]
[ 14  45  -5 -62 -24   2]
[ 21  57  15 -42 -18   9]
[ 21  66   0 -63 -27   3]
[3 3 9 0 0 3]
[3 3 9 0 0 3]


In [40]:
# Should give collin, totally nonreduced locus (i.e. O_{4,col}) without the 3 factor out front
# Comes from O_{4,col} = 3(P_2 - PH + l + p)(P^2 - P_2)
intersection_product(M,B,[2,0,0,0,1,0,0])-intersection_product(M,B,[3,1,0,0,0,0,0])+intersection_product(M,B,[2,0,0,0,0,1,0])+intersection_product(M,B,[2,0,0,0,0,0,1])-intersection_product(M,B,[0,0,0,0,2,0,0])+intersection_product(M,B,[1,1,0,0,1,0,0])-intersection_product(M,B,[0,0,0,0,1,1,0])-intersection_product(M,B,[0,0,0,0,1,0,1])

array([-9,  6,  2, -2, -3,  6, -8,  0, 18,  0,  0,  0,  0])

In [41]:
# Check X_{1,4}
# Add [0,0,0,0,0,1,1] to each entry
intersection_product(M,B,[2,0,0,0,1,1,1])-intersection_product(M,B,[3,1,0,0,0,1,1])+intersection_product(M,B,[2,0,0,0,0,2,1])+intersection_product(M,B,[2,0,0,0,0,1,2])-intersection_product(M,B,[0,0,0,0,2,1,1])+intersection_product(M,B,[1,1,0,0,1,1,1])-intersection_product(M,B,[0,0,0,0,1,2,1])-intersection_product(M,B,[0,0,0,0,1,1,2])

array([9, 0])

In [42]:
# Check X_{1,3}
# Add [0,0,0,0,0,0,2] to each entry
intersection_product(M,B,[2,0,0,0,1,0,2])-intersection_product(M,B,[3,1,0,0,0,0,2])+intersection_product(M,B,[2,0,0,0,0,1,2])+intersection_product(M,B,[2,0,0,0,0,0,3])-intersection_product(M,B,[0,0,0,0,2,0,2])+intersection_product(M,B,[1,1,0,0,1,0,2])-intersection_product(M,B,[0,0,0,0,1,1,2])-intersection_product(M,B,[0,0,0,0,1,0,3])

array([-9,  9])

In [43]:
# Gives X_{2,5} intersection numbers. (1/3) and 3 cancel out.
intersection_product(M,B,[2,1,0,0,1,0,1])-intersection_product(M,B,[3,2,0,0,0,0,1])+intersection_product(M,B,[2,1,0,0,0,1,1])+intersection_product(M,B,[2,1,0,0,0,0,2])-intersection_product(M,B,[0,1,0,0,2,0,1])+intersection_product(M,B,[1,2,0,0,1,0,1])-intersection_product(M,B,[0,1,0,0,1,1,1])-intersection_product(M,B,[0,1,0,0,1,0,2])

array([  0, -27,  27,   0,   0,   9])

In [44]:
#First 7 digits encode a monomial, last digit is MULTIPLICITY not a value
#Seems to work
# This is stuff for nu_3, locus of schemes containing a fixed point. Namely, showing (nu_3)^3 = 1.
K = ([[0,0,1,0,0,0,0,3],[0,1,0,0,1,0,0,-1],[1,0,0,0,0,1,0,1]])
K2 = []
for j in K:
    for k in K:
        K2.append(np.append((np.array(j[:7])+np.array(k[:7])),j[7]*k[7]))

print(np.asarray(K2))

K3 = []
for j in K:
    for k in K2:
        K3.append(np.append((np.array(j[:7])+np.array(k[:7])),j[7]*k[7]))
        
print(np.asarray(K3))

[[ 0  0  2  0  0  0  0  9]
 [ 0  1  1  0  1  0  0 -3]
 [ 1  0  1  0  0  1  0  3]
 [ 0  1  1  0  1  0  0 -3]
 [ 0  2  0  0  2  0  0  1]
 [ 1  1  0  0  1  1  0 -1]
 [ 1  0  1  0  0  1  0  3]
 [ 1  1  0  0  1  1  0 -1]
 [ 2  0  0  0  0  2  0  1]]
[[ 0  0  3  0  0  0  0 27]
 [ 0  1  2  0  1  0  0 -9]
 [ 1  0  2  0  0  1  0  9]
 [ 0  1  2  0  1  0  0 -9]
 [ 0  2  1  0  2  0  0  3]
 [ 1  1  1  0  1  1  0 -3]
 [ 1  0  2  0  0  1  0  9]
 [ 1  1  1  0  1  1  0 -3]
 [ 2  0  1  0  0  2  0  3]
 [ 0  1  2  0  1  0  0 -9]
 [ 0  2  1  0  2  0  0  3]
 [ 1  1  1  0  1  1  0 -3]
 [ 0  2  1  0  2  0  0  3]
 [ 0  3  0  0  3  0  0 -1]
 [ 1  2  0  0  2  1  0  1]
 [ 1  1  1  0  1  1  0 -3]
 [ 1  2  0  0  2  1  0  1]
 [ 2  1  0  0  1  2  0 -1]
 [ 1  0  2  0  0  1  0  9]
 [ 1  1  1  0  1  1  0 -3]
 [ 2  0  1  0  0  2  0  3]
 [ 1  1  1  0  1  1  0 -3]
 [ 1  2  0  0  2  1  0  1]
 [ 2  1  0  0  1  2  0 -1]
 [ 2  0  1  0  0  2  0  3]
 [ 2  1  0  0  1  2  0 -1]
 [ 3  0  0  0  0  3  0  1]]


In [45]:
#This shows that (nu_3)^3 = 1, which it needs to be. Great!
totaling = 0
for k in K3:
    totaling += intersection_product(M,B,k[:7])*k[7]
    #print(intersection_product(M,B,k[:7]))
print(totaling)

[1]


In [46]:
#Computing: collin schemes contained in a line and including a fixed point in that line
print(intersection_product(M,B,[2,1,0,0,0,0,2]) - intersection_product(M,B,[0,1,0,0,1,0,2]))

[ 0  9 -9  9  0  0]


In [47]:
#This is the matrix parametrizing O_{3,coll}. The first seven entries are the monomial, the eigth is coefficient.
COL3 = np.asarray([[2,1,0,0,0,0,0,2],
        [3,0,0,0,0,0,0,-2],
        [0,1,0,0,1,0,0,-2],
        [1,0,0,0,1,0,0,2]])

In [48]:
#Doublechecking for X_{3,13}, nonred coll schemes in a plane that are collin with pt
X3_13TOT = [0,0,0,0,0,0,0,0,0,0]
for i in COL3:
    #print(i[:7]+[1,0,0,0,0,0,0])
    X3_13TOT = X3_13TOT + i[7]*intersection_product(M,B,i[:7]+[1,0,0,0,0,0,1])
    X3_13TOT = X3_13TOT + i[7]*intersection_product(M,B,i[:7]+[0,1,0,0,0,0,1])
print(X3_13TOT)

[  0  36 -36 -54 -54 -36   0 162  36   0]


In [49]:
#Computing the intersection numbers of X_{2,9}
print(2*intersection_product(M,B,[2,1,0,0,0,0,2])-2*intersection_product(M,B,[3,0,0,0,0,0,2])-2*intersection_product(M,B,[0,1,0,0,1,0,2])+2*intersection_product(M,B,[1,0,0,0,1,0,2]))

[  0  36 -36  36   0   0]


In [50]:
#Investigating someth related to X_{2,7}, X_{2,8}, namely
#(p\ell)(O_{3,coll})(1/3) = S_{7} + S_{9}
print(2*intersection_product(M,B,[2,1,0,0,0,1,1])-2*intersection_product(M,B,[3,0,0,0,0,1,1])-2*intersection_product(M,B,[0,1,0,0,1,1,1])+2*intersection_product(M,B,[1,0,0,0,1,1,1]))

[-12 -54  18  18  12   0]


In [51]:
#This is the matrix parametrizing O_{4,col}. First seven entries are monomial, eigth is coeff.
COL4 = np.array([[2,0,0,0,1,0,0,3],
        [3,1,0,0,0,0,0,-3],
        [2,0,0,0,0,1,0,3],
        [2,0,0,0,0,0,1,3],
        ###############
        [0,0,0,0,2,0,0,-3],
        [1,1,0,0,1,0,0,3],
        [0,0,0,0,1,1,0,-3],
        [0,0,0,0,1,0,1,-3]])

In [52]:
X26 = [0,0,0,0,0,0]
for k  in COL4:
    tempH = np.array(k[:7]) + np.array([0,1,0,0,0,0,1])
    tempP = np.array(k[:7]) + np.array([1,0,0,0,0,0,1])
    X26 = np.array(X26) + k[7]*intersection_product(M,B,tempH) + k[7]*intersection_product(M,B,tempP)
print(X26)
#This gives the desired result for X_{2,6} after appropriate scaling: mult by (1/9)
#and you get S_1 : 3(\beta - \gamma + 2\delta + \epsilon)

[-27 -81   0  81  27   0]


In [53]:
# This is the matrix parametrizing O_{4,max}. First seven entries are monomial, eigth is coeff
# This data was also earlier in the code, but is more condensed now.
MAX4 = np.asarray([[2,0,0,0,1,0,0,-2],
      [1,1,0,0,1,0,0,-1],
      [0,2,0,0,1,0,0,1],
      [0,0,0,0,1,0,1,-3],
      [0,0,0,0,2,0,0,9],
      ################
       [3,1,0,0,0,0,0,2],
       [2,2,0,0,0,0,0,1],
       [1,3,0,0,0,0,0,-1],
       [1,1,0,0,0,0,1,3],
       [1,1,0,0,1,0,0,-9],
       ###############
       [2,0,0,0,0,0,1,-2],
       [1,1,0,0,0,0,1,-1],
       [0,2,0,0,0,0,1,1],
       [0,0,0,0,0,0,2,-3],
       [0,0,0,0,1,0,1,9],
       ################
       [2,0,0,0,0,1,0,-2],
       [1,1,0,0,0,1,0,-1],
       [0,2,0,0,0,1,0,1],
       [0,0,0,0,0,1,1,-3],
       [0,0,0,0,1,1,0,9]
      ])
#[-2,-1,1,-3,9,2,1,-1,3,-9,-2,-1,1,-3,9,-2,-1,1,-3,9]

In [54]:
# Int numbers for figuring out class of O_{4,max}.
# Doublechecking with prior list.
MAX4CLASSTOT = [0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in MAX4:
    MAX4CLASSTOT = MAX4CLASSTOT + i[7]*intersection_product(M,B,i[:7])
print(MAX4CLASSTOT)

[ 0  9  3  0  0  9  0  1 27  9  0  0  0]


In [55]:
# This computes the intersection numbers of O_{4,max}*P_3
# Variable and temp variable in working order.
MAX4PLANETOT = [0,0,0,0,0,0]
for k in MAX4:
    temp = np.array(k[:7]) + np.array([0,0,1,0,0,0,0])
    MAX4PLANETOT = np.array(MAX4PLANETOT) + k[7]*intersection_product(M,B,temp)
print(MAX4PLANETOT)

[0 0 0 9 3 0]


In [56]:
# This computes the intersection numbers of O_{4,max}*P*\ell
# Variable and temp variable in working order.
MAX4PlTOT = [0,0,0,0,0,0]
for k in MAX4:
    temp = np.array(k[:7]) + np.array([1,0,0,0,0,1,0])
    MAX4PlTOT = np.array(MAX4PlTOT) + k[7]*intersection_product(M,B,temp)
print(MAX4PlTOT)

[3 3 9 0 0 3]


In [57]:
# This computes the intersection numbers for planar fat points supported at a fixed pt
# recall that K is the matrix for data related to nu_3: the locus of schemes containing a fixed point 
MAX4PT_TOT = [0,0,0,0,0,0]
for k in MAX4:
    for j in K:
        temp = np.array(k[:7]) + np.array(j[:7])
        #print(temp)
        #print(intersection_product(M,B,temp))
        MAX4PT_TOT = MAX4PT_TOT + k[7]*j[7]*intersection_product(M,B,temp)
print(MAX4PT_TOT)

[3 3 0 0 0 0]


In [58]:
#This suggests that X_{2,2} has intersection numbers [0,0,9,0,0,3]

In [59]:
#Now to compute X_{2,4}: totally nonreduced, collinear schemes supported at a fixed pt.
X24TOT = [0,0,0,0,0,0]
for k in COL4:
    for j in K:
        temp = np.array(k[:7]) + np.array(j[:7])
        X24TOT = X24TOT + k[7]*j[7]*intersection_product(M,B,temp)
print(X24TOT)

[ 6 27  0  0  0  0]


In [60]:
#Encodes O_{2,nonred} = 3(P_2 - PH + \ell + p). First 7 digits encode monomial
#8th digit encodes coeff
NONRED2 = np.array([[0,0,0,0,1,0,0,3],
                   [1,1,0,0,0,0,0,-3],
                   [0,0,0,0,0,1,0,3],
                   [0,0,0,0,0,0,1,3]])

In [61]:
#Encodes Y_2*H = -P_3*PH - P_3H^2 + P_2 p H
Y2H = np.array([[1,1,1,0,0,0,0,-1],
              [0,2,1,0,0,0,0,-1],
              [0,1,0,0,1,0,1,1]])

In [62]:
#Computes locus of totally nonreduced schemes supp at P, length two in L. Two dimensions 
#come from the two dims of freedom of second order direction
NONREDLINE2TOT = [0,0,0,0,0,0]
for k in NONRED2:
    for j in Y2H:
        temp = np.array(k[:7]) + np.array(j[:7])
        NONREDLINE2TOT = NONREDLINE2TOT + k[7]*j[7]*intersection_product(M,B,temp)
        #print(NONREDLINE2TOT)
print(NONREDLINE2TOT)

[0 9 0 0 0 0]


In [64]:
N4n4TOT = [0]
POINT = np.array([[0,0,1,0,0,0,0,3],
                 [0,1,0,0,1,0,0,-1],
                 [1,0,0,0,0,1,0,1]])
FARRAY = np.array([[1,0,0,0,0,0,0,1],[0,1,0,0,0,0,0,1]])
N4ARRAY = np.array([[0,0,1,0,0,0,0,-3],
                   [1,0,0,0,1,0,0,1],
                   [0,1,0,0,1,0,0,1]])

In [65]:
TERMCOUNTER = 0
print(N4n4TOT)
for k in NONRED2:
    for j in POINT:
        for l in FARRAY:
            for i in N4ARRAY:
                temp = np.array(k[:7]) + np.array(j[:7]) + np.array(l[:7]) + np.array(i[:7])
                N4n4TOT = N4n4TOT + k[7]*j[7]*l[7]*i[7]*intersection_product(M,B,temp)
                print (temp)
                print(N4n4TOT)
                TERMCOUNTER = TERMCOUNTER + 1
print(N4n4TOT)
print(TERMCOUNTER)

[0]
[1 0 2 0 1 0 0]
[0]
[2 0 1 0 2 0 0]
[-9]
[1 1 1 0 2 0 0]
[0]
[0 1 2 0 1 0 0]
[0]
[1 1 1 0 2 0 0]
[9]
[0 2 1 0 2 0 0]
[0]
[1 1 1 0 2 0 0]
[9]
[2 1 0 0 3 0 0]
[-6]
[1 2 0 0 3 0 0]
[-9]
[0 2 1 0 2 0 0]
[-18]
[1 2 0 0 3 0 0]
[-21]
[0 3 0 0 3 0 0]
[0]
[2 0 1 0 1 1 0]
[-9]
[3 0 0 0 2 1 0]
[18]
[2 1 0 0 2 1 0]
[9]
[1 1 1 0 1 1 0]
[18]
[2 1 0 0 2 1 0]
[9]
[1 2 0 0 2 1 0]
[0]
[2 1 2 0 0 0 0]
[27]
[3 1 1 0 1 0 0]
[0]
[2 2 1 0 1 0 0]
[0]
[1 2 2 0 0 0 0]
[-27]
[2 2 1 0 1 0 0]
[-27]
[1 3 1 0 1 0 0]
[0]
[2 2 1 0 1 0 0]
[0]
[3 2 0 0 2 0 0]
[42]
[2 3 0 0 2 0 0]
[0]
[1 3 1 0 1 0 0]
[27]
[2 3 0 0 2 0 0]
[-15]
[1 4 0 0 2 0 0]
[-27]
[3 1 1 0 0 1 0]
[-54]
[4 1 0 0 1 1 0]
[-60]
[3 2 0 0 1 1 0]
[-18]
[2 2 1 0 0 1 0]
[-18]
[3 2 0 0 1 1 0]
[24]
[2 3 0 0 1 1 0]
[0]
[1 0 2 0 0 1 0]
[0]
[2 0 1 0 1 1 0]
[9]
[1 1 1 0 1 1 0]
[0]
[0 1 2 0 0 1 0]
[0]
[1 1 1 0 1 1 0]
[-9]
[0 2 1 0 1 1 0]
[0]
[1 1 1 0 1 1 0]
[-9]
[2 1 0 0 2 1 0]
[0]
[1 2 0 0 2 1 0]
[9]
[0 2 1 0 1 1 0]
[18]
[1 2 0 0 2 1 0]
[27]
[0 3 0 0 2 1 0]
[0]
[2

In [66]:
##### This begins comps of classes that we need for paper... Things that make up
##### extremal rays of suborbits. #####

In [67]:
#Max'l ideals incident to a line
max_supp_line = [0,0,0,0,0,0,0,0,0,0]
ctr7 = 0
for i in range(0,20):
    max_supp_line = max_supp_line + maxc[i]*intersection_product(M,B,maxm[i]+[0,0,0,0,0,1,0])
    ctr7 = ctr7 + 1
    print(max_supp_line)
print(max_supp_line)
print(ctr7)

[ -2 -18   6  28  -4  14  -6 -16  -2   2]
[ -1 -15   9  20  10  13  -3 -41  -9   1]
[  0 -18  18  45  18  20   1 -16  -2   4]
[  0 -18  18  33  27  20   1 -43  -8   1]
[ 0  0  0  6  0  2  1 38 10  1]
[  -6    4  -28   10 -100   -6  -23  130   34    3]
[ -6 -10 -20  56 -98   6 -19 200  54   9]
[  -9  -18  -45  -14 -144  -14  -37  130   34    0]
[  -9  -27  -33   40 -132    1  -31  205   55    6]
[  0   0  -6 -32  -6  -8  -4 -20  -8  -3]
[  0  -6   0 -40  18  -2  -4 -56 -18  -5]
[  0  -3  -4 -58  14  -7  -6 -81 -25  -7]
[  1   1   5 -33  32   0   1 -56 -18  -4]
[  1   1  -1 -54  26  -6   1 -83 -24  -7]
[  1   1  -1 -18  -1  -6   1  -2  -6   2]
[  3  15  -3 -42   7 -18   7 -42 -18   0]
[  2  14 -10 -62  -5 -24   2 -62 -24  -3]
[  3  21  -3 -42  15 -18   9 -42 -18   0]
[  3  21  -9 -63   0 -27   3 -63 -27   0]
[3 3 9 0 9 0 3 0 0 0]
[3 3 9 0 9 0 3 0 0 0]
20


In [68]:
#Max'l ideals incident to a plane and coplanar with a fixed pt P. O_{4,max}*PH
max_PH = [0,0,0,0,0,0,0,0,0,0]
ctr8 = 0
for i in range(0,20):
    max_PH = max_PH + maxc[i]*intersection_product(M,B,maxm[i]+[1,1,0,0,0,0,0])
    ctr8 = ctr8 + 1
    print(max_PH)
print(max_PH)
print(ctr8)

[  -6   -8  -28   24 -108   -4  -24   78   28    2]
[ -6 -22 -14  63 -96  10 -21  33  20   4]
[  -9  -36  -18  108 -135   18  -27  138   45   13]
[  -9  -45   -9  126 -126   27  -27   66   33   10]
[ 0  0  0  0  0  0  0 30  6  1]
[  24  108  -24 -320  218 -100   66  110   10  -27]
[  12   96  -63 -280   58  -98   24  310   56  -15]
[   9  135 -108 -480   18 -144   -9   30  -14  -48]
[   0  126 -126 -381 -108 -132  -30  285   40  -24]
[   0    0    0  -30    0   -6   -3 -120  -32   -6]
[  -6  -24    6   54  -66   18  -21 -186  -40   -2]
[  -3  -21   12   21  -24   14  -14 -271  -58  -10]
[   0  -27   36  106    9   32    7 -166  -33    5]
[   0  -27   30   43   30   26   -2 -274  -54  -10]
[  0   0   3 -11   3  -1  -2 -58 -18  -1]
[   6   -4   31  -15  103    7   22 -150  -42   -3]
[   6   10   23  -61  101   -5   18 -220  -62   -9]
[   9   18   48    9  147   15   36 -150  -42    0]
[   9   27   36  -45  135    0   30 -225  -63   -6]
[ 0  0  9 27  9  9  3  0  0  3]
[ 0  0  9 27  9  9  

In [69]:
#checking that some additions are executed correctly
for i in range(0,20):
    print(maxm[i]+[1,1,0,0,0,0,0]+[0,0,0,1,0,0,0])
print(len(maxm))

[3 1 0 1 1 0 0]
[2 2 0 1 1 0 0]
[1 3 0 1 1 0 0]
[1 1 0 1 1 0 1]
[1 1 0 1 2 0 0]
[4 2 0 1 0 0 0]
[3 3 0 1 0 0 0]
[2 4 0 1 0 0 0]
[2 2 0 1 0 0 1]
[2 2 0 1 1 0 0]
[3 1 0 1 0 0 1]
[2 2 0 1 0 0 1]
[1 3 0 1 0 0 1]
[1 1 0 1 0 0 2]
[1 1 0 1 1 0 1]
[3 1 0 1 0 1 0]
[2 2 0 1 0 1 0]
[1 3 0 1 0 1 0]
[1 1 0 1 0 1 1]
[1 1 0 1 1 1 0]
20


In [70]:
#Max'l ideals coplanar with line. O_{4,max}*P_2
#That last entry, O_{4,max}*P_2*\beta was observed before.
max_P2 = [0,0,0,0,0,0,0,0,0,0]
ctr9 = 0
for i in range(0,20):
    max_P2 = max_P2 + maxc[i]*intersection_product(M,B,maxm[i]+[0,0,0,0,1,0,0])
    ctr9 = ctr9 + 1
    print(max_P2)
print(max_P2)
print(ctr9)
#print(maxm[17])
#print(maxc[17])
#print(maxm[16])
#print(maxc[16])
#print(maxm[15])
#print(maxc[15])
#print(maxc[4]*intersection_product(M,B,maxm[4]+[0,0,0,0,1,0,0]))
#print(maxm[4]+[0,0,0,0,1,0,0])
#print(intersection_product(M,B,[0,0,0,0,3,0,0]))
#print(5*intersection_product(M,B,[0,0,2,0,0,0,0])-2*intersection_product(M,B,[0,1,1,0,1,0,0]))

[  2  22 -10 -28  -8 -18   6  28   6  -2]
[  1  17 -11 -14 -22 -15   3  32   9  -1]
[  0  18 -18 -18 -36 -18   0  72  18   0]
[  0  18 -18  -9 -45 -18   0  63  18   0]
[0 0 0 0 0 0 0 0 0 0]
[  6   8  28 -24 108   4  24 -78 -28  -2]
[  6  22  14 -63  96 -10  21 -33 -20  -4]
[   9   36   18 -108  135  -18   27 -138  -45  -13]
[   9   45    9 -126  126  -27   27  -66  -33  -10]
[  0   0   0   0   0   0   0 -30  -6  -1]
[  0   6  -6   6 -24  -6   0 -18   0  -1]
[  0   3  -3  12 -21  -3   0 -42  -4  -2]
[  0   0   0  36 -27   1   2  -2   5   3]
[  0   0   0  30 -27   1  -1 -38  -1   0]
[  0   0   0   3   0   1  -1 -11  -1   0]
[ -2 -18   6  31  -4  15  -7 -27  -3   2]
[ -1 -15   9  23  10  14  -4 -52 -10   1]
[  0 -18  18  48  18  21   0 -27  -3   4]
[  0 -18  18  36  27  21   0 -54  -9   1]
[ 0  0  0  9  0  3  0 27  9  1]
[ 0  0  0  9  0  3  0 27  9  1]
20


In [71]:
# Redundant testing.
max_P2test = [0,0,0,0,0,0,0,0,0,0]
for i in range(0,20):
    max_P2test = max_P2test + maxc[i]*intersection_product(M,B,maxm[i]+[0,0,0,0,1,0,0])
    #ctr9 = ctr9 + 1
    print(max_P2test)
print(max_P2test)
#print(ctr9)

[  2  22 -10 -28  -8 -18   6  28   6  -2]
[  1  17 -11 -14 -22 -15   3  32   9  -1]
[  0  18 -18 -18 -36 -18   0  72  18   0]
[  0  18 -18  -9 -45 -18   0  63  18   0]
[0 0 0 0 0 0 0 0 0 0]
[  6   8  28 -24 108   4  24 -78 -28  -2]
[  6  22  14 -63  96 -10  21 -33 -20  -4]
[   9   36   18 -108  135  -18   27 -138  -45  -13]
[   9   45    9 -126  126  -27   27  -66  -33  -10]
[  0   0   0   0   0   0   0 -30  -6  -1]
[  0   6  -6   6 -24  -6   0 -18   0  -1]
[  0   3  -3  12 -21  -3   0 -42  -4  -2]
[  0   0   0  36 -27   1   2  -2   5   3]
[  0   0   0  30 -27   1  -1 -38  -1   0]
[  0   0   0   3   0   1  -1 -11  -1   0]
[ -2 -18   6  31  -4  15  -7 -27  -3   2]
[ -1 -15   9  23  10  14  -4 -52 -10   1]
[  0 -18  18  48  18  21   0 -27  -3   4]
[  0 -18  18  36  27  21   0 -54  -9   1]
[ 0  0  0  9  0  3  0 27  9  1]
[ 0  0  0  9  0  3  0 27  9  1]


In [72]:
###These are the guys appearing in above:P_2, and their ints with (4th,6th,8th,9th entry)
###Hence: PH^2(done),P\ell,H^3,H\ell
#for i in range(0,20):
    #print(maxm[i]+[0,0,0,0,1,0,0]+[1,2,0,0,0,0,0])
for i in range(0,20):
    #print(maxm[i]+[0,0,0,0,1,0,0]+[])
    print(maxm[i]+[0,0,0,0,1,0,0]+[0,0,0,1,0,0,0])

[2 0 0 1 2 0 0]
[1 1 0 1 2 0 0]
[0 2 0 1 2 0 0]
[0 0 0 1 2 0 1]
[0 0 0 1 3 0 0]
[3 1 0 1 1 0 0]
[2 2 0 1 1 0 0]
[1 3 0 1 1 0 0]
[1 1 0 1 1 0 1]
[1 1 0 1 2 0 0]
[2 0 0 1 1 0 1]
[1 1 0 1 1 0 1]
[0 2 0 1 1 0 1]
[0 0 0 1 1 0 2]
[0 0 0 1 2 0 1]
[2 0 0 1 1 1 0]
[1 1 0 1 1 1 0]
[0 2 0 1 1 1 0]
[0 0 0 1 1 1 1]
[0 0 0 1 2 1 0]


In [73]:
for i in range(0,20):
    print(maxm[i]+[1,0,0,0,1,1,0])

[3 0 0 0 2 1 0]
[2 1 0 0 2 1 0]
[1 2 0 0 2 1 0]
[1 0 0 0 2 1 1]
[1 0 0 0 3 1 0]
[4 1 0 0 1 1 0]
[3 2 0 0 1 1 0]
[2 3 0 0 1 1 0]
[2 1 0 0 1 1 1]
[2 1 0 0 2 1 0]
[3 0 0 0 1 1 1]
[2 1 0 0 1 1 1]
[1 2 0 0 1 1 1]
[1 0 0 0 1 1 2]
[1 0 0 0 2 1 1]
[3 0 0 0 1 2 0]
[2 1 0 0 1 2 0]
[1 2 0 0 1 2 0]
[1 0 0 0 1 2 1]
[1 0 0 0 2 2 0]


In [74]:
### This is the section for the collinear and totally nonreduced schemes

In [75]:
# Totally nonreduced collinear schemes that are collinear with some P. This is (1/3)O_4,col*M
# In progress
# Recall that COL4 params O_4col as 8 digit entries.
# Recall that P^2 + PH - 3P2 = M
coll_tnr_M_TOT = [0,0,0,0,0,0,0,0,0,0]
ctr10 = 0

for i in COL4:
    coll_tnr_M_TOT = coll_tnr_M_TOT + i[7]*intersection_product(M,B,i[:7]+[2,0,0,0,0,0,0])
    #print(coll_tnr_M_TOT)
    coll_tnr_M_TOT = coll_tnr_M_TOT + i[7]*intersection_product(M,B,i[:7]+[1,1,0,0,0,0,0])
    #print(coll_tnr_M_TOT)
    coll_tnr_M_TOT = coll_tnr_M_TOT - 3*i[7]*intersection_product(M,B,i[:7]+[0,0,0,0,1,0,0])
    ctr10 = ctr10 + 1
    #print(coll_tnr_M_TOT)
print(coll_tnr_M_TOT)
print(ctr10)

[  0 -18  -9   0   0   0   0  81  27   0]
8


In [76]:
#Int numbers for figuring out class of O_{4,col}
COL4CLASSTOT = [0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in COL4:
    COL4CLASSTOT = COL4CLASSTOT + i[7]*intersection_product(M,B,i[:7])
print(COL4CLASSTOT)

[-27  18   6  -6  -9  18 -24   0  54   0   0   0   0]


In [77]:
#O_4 collinear locus once you do the linear algebra to get it into
#the EL basis of A_5(Hilb3P3)
O4COLLDATA = np.asarray([
    [1,0,1,0,0,0,0,-42],
    [0,1,1,0,0,0,0,66],
    [0,2,0,0,1,0,0,-21],
    [1,1,0,0,1,0,0,0],
    [0,0,0,0,1,1,0,-3],
    [0,0,0,0,2,0,0,6],
    [0,0,0,0,1,0,1,18],
    [2,2,0,0,0,0,0,-6],[1,3,0,0,0,0,0,-6], #special double basis elt
    [1,1,0,0,0,1,0,36],
    [1,0,0,1,0,0,0,36],
    [0,2,0,0,0,1,0,-9],
    [0,0,0,0,0,2,0,18],
    [0,0,0,0,0,1,1,18]
]) 

In [78]:
#Alignment of these with cell from two ago suggests that everything is fine.
COLLMTOT = [0,0,0,0,0,0,0,0,0,0]
for i in O4COLLDATA:
    COLLMTOT = COLLMTOT + i[7]*intersection_product(M,B,i[:7]+[2,0,0,0,0,0,0])
    COLLMTOT = COLLMTOT + i[7]*intersection_product(M,B,i[:7]+[1,1,0,0,0,0,0])
    COLLMTOT = COLLMTOT + (-3)*i[7]*intersection_product(M,B,i[:7]+[0,0,0,0,1,0,0])
print(COLLMTOT)

[  0 -18  -9   0   0   0   0  81  27   0]


In [79]:
#Totally nonreduced collinear guys that are contained in some plane. This is (1/3)O_4,col*p
# Recall that COL4 params O_4col as 8 digit entries.
#This yields the right thing
coll_tnr_plane = [0,0,0,0,0,0,0,0,0,0]
ctr11 = 0

for i in COL4:
    coll_tnr_plane = coll_tnr_plane + i[7]*intersection_product(M,B,i[:7]+[0,0,0,0,0,0,1])
    ctr11 = ctr11+1
print(coll_tnr_plane)
print(ctr11)

[ -9 -27   0  81 -81  27 -27   0   0   9]
8


In [80]:
#Totally nonreduced collinear guys incident to a line. This is (1/3)?O_4,col*ell
# Recall that COL4 params O_4col as 8 digit entries
# 6 in first entry is interesting.
coll_tnr_line = [0,0,0,0,0,0,0,0,0,0]
ctr12 = 0

for i in COL4:
    coll_tnr_line = coll_tnr_line + i[7]*intersection_product(M,B,i[:7]+[0,0,0,0,0,1,0])
    ctr12 = ctr12+1
print(coll_tnr_line)
print(ctr12)

[ 6  0 18  0 81  0 27  0  0  0]
8


In [81]:
# THIS BEGINS THE SECTION OF COLLINEAR AND NONREDUCED
#Recall that COL3 parametrizes O_3,col as 8-entry arrays

In [82]:
for i in maxm:
    j = np.asarray(i+[0,0,0,0,1,0,0]+[0,0,0,1,0,0,0])
    print(j)
    
print("LINE BREAK")
for i in range(0,20):
    print(np.asarray(maxm[i]+[0,0,0,0,1,0,0]+[0,0,0,1,0,0,0]))

    

[2 0 0 1 2 0 0]
[1 1 0 1 2 0 0]
[0 2 0 1 2 0 0]
[0 0 0 1 2 0 1]
[0 0 0 1 3 0 0]
[3 1 0 1 1 0 0]
[2 2 0 1 1 0 0]
[1 3 0 1 1 0 0]
[1 1 0 1 1 0 1]
[1 1 0 1 2 0 0]
[2 0 0 1 1 0 1]
[1 1 0 1 1 0 1]
[0 2 0 1 1 0 1]
[0 0 0 1 1 0 2]
[0 0 0 1 2 0 1]
[2 0 0 1 1 1 0]
[1 1 0 1 1 1 0]
[0 2 0 1 1 1 0]
[0 0 0 1 1 1 1]
[0 0 0 1 2 1 0]
LINE BREAK
[2 0 0 1 2 0 0]
[1 1 0 1 2 0 0]
[0 2 0 1 2 0 0]
[0 0 0 1 2 0 1]
[0 0 0 1 3 0 0]
[3 1 0 1 1 0 0]
[2 2 0 1 1 0 0]
[1 3 0 1 1 0 0]
[1 1 0 1 1 0 1]
[1 1 0 1 2 0 0]
[2 0 0 1 1 0 1]
[1 1 0 1 1 0 1]
[0 2 0 1 1 0 1]
[0 0 0 1 1 0 2]
[0 0 0 1 2 0 1]
[2 0 0 1 1 1 0]
[1 1 0 1 1 1 0]
[0 2 0 1 1 1 0]
[0 0 0 1 1 1 1]
[0 0 0 1 2 1 0]


In [83]:
#Computing O_{1,nonred}*\nu_3 This is \nu_3*(2(H-P))
NONREDPTTOT = [0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in POINT:
    temp1 = i[:7]+[0,1,0,0,0,0,0]
    temp2 = i[:7]+[1,0,0,0,0,0,0]
    NONREDPTTOT = NONREDPTTOT + i[7]*intersection_product(M,B,temp1) - i[7]*intersection_product(M,B,temp2)
print(NONREDPTTOT)

[0 0 0 0 0 0 2 0 0 3 0 0 0]


In [85]:
print(intersection_product(M,B,[1,0,1,0,0,1,0])+intersection_product(M,B,[0,1,1,0,0,1,0]))
#print(intersection_product(M,B,[0,1,1,0,0,1,0]))

[ 0  0  0  3 -3  0  0  6  2  0]


In [86]:
print(intersection_product(M,B,[0,1,1,0,0,1,0])+intersection_product(M,B,[0,1,1,0,1,0,0])-3*intersection_product(M,B,[0,0,2,0,0,0,0]))
#print(intersection_product(M,B,[0,1,1,0,1,0,0]))
#print(intersection_product(M,B,[0,0,2,0,0,0,0]))

[ 0  0  0  3 -3  0  0  6  2  0]


In [87]:
TOTLYNONRED = [
    [0,0,0,0,1,0,0,3],
    [1,1,0,0,0,0,0,-3],
    [0,0,0,0,0,1,0,3],
    [0,0,0,0,0,0,1,3]
]

In [88]:
#Computations related to the class of nu_4
NUFOURTOT = [0,0,0,0,0,0,0,0,0,0]
NUFOURCOUNTER = 0
for i in POINT:
    for j in TOTLYNONRED:
        NUFOURTOT = NUFOURTOT + i[7]*j[7]*intersection_product(M,B,i[:7]+j[:7]+[1,0,0,0,0,0,0])
        #print(i[:7]+j[:7]+[1,0,0,0,0,0,0])
        NUFOURCOUNTER = NUFOURCOUNTER + 1
        #print(NUFOURTOT)
        NUFOURTOT = NUFOURTOT + i[7]*j[7]*intersection_product(M,B,i[:7]+j[:7]+[0,1,0,0,0,0,0])
        NUFOURCOUNTER = NUFOURCOUNTER + 1
print(NUFOURTOT)
print(NUFOURCOUNTER)

[0 9 0 0 0 0 0 0 0 0]
24


In [89]:
# DATA FOR W1, W2, auxiliary classes in the appendix. First seven digits keep track of the monomial, and then last digit is coeff.
# In order, they should be:
# P_3 P, P_3 H, P_2 H^2, P_2 HP, P_2 l, P_2^2, P_2 p, (P^2H^2 + PH^3) (split), 
# PH ell, P beta, H^2 l, l^2, lp
W1DATA = np.asarray([
    [1,0,1,0,0,0,0,-10],
    [0,1,1,0,0,0,0,10],
    [0,2,0,0,1,0,0,-2],
    [1,1,0,0,1,0,0,2],
    [0,0,0,0,1,1,0,-4],
    [0,0,0,0,2,0,0,0],
    [0,0,0,0,1,0,1,4],
    [2,2,0,0,0,0,0,-2],[1,3,0,0,0,0,0,-2], #special double basis elt
    [1,1,0,0,0,1,0,10],
    [1,0,0,1,0,0,0,8],
    [0,2,0,0,0,1,0,0],
    [0,0,0,0,0,2,0,0],
    [0,0,0,0,0,1,1,0]
])

W2DATA = np.asarray([
    [1,0,1,0,0,0,0,10],
    [0,1,1,0,0,0,0,-2],
    [0,2,0,0,1,0,0,0],
    [1,1,0,0,1,0,0,-2],
    [0,0,0,0,1,1,0,2],
    [0,0,0,0,2,0,0,0],
    [0,0,0,0,1,0,1,-4],
    [2,2,0,0,0,0,0,2],[1,3,0,0,0,0,0,2], #special double basis elt
    [1,1,0,0,0,1,0,-8],
    [1,0,0,1,0,0,0,-8],
    [0,2,0,0,0,1,0,0],
    [0,0,0,0,0,2,0,0],
    [0,0,0,0,0,1,1,0]
]) 

In [90]:
W1COLLTOT = [0,0,0,0,0,0,0,0,0,0]
W1CTR = 0
for i in W1DATA:
    W1COLLTOT = W1COLLTOT+i[7]*(intersection_product(M,B,i[:7]+[2,0,0,0,0,0,0]))
    W1CTR+=1
    W1COLLTOT = W1COLLTOT+(-1)*i[7]*(intersection_product(M,B,i[:7]+[0,0,0,0,1,0,0]))
    W1CTR+=1
print(W1COLLTOT)
print(W1CTR)

[ 0 -8  2  4  8  4  0  2  2  0]
28


In [91]:
W2COLLTOT = [0,0,0,0,0,0,0,0,0,0]
W2CTR = 0
for i in W2DATA:
    W2COLLTOT = W2COLLTOT+i[7]*(intersection_product(M,B,i[:7]+[2,0,0,0,0,0,0]))
    W2CTR+=1
    W2COLLTOT = W2COLLTOT+(-1)*i[7]*(intersection_product(M,B,i[:7]+[0,0,0,0,1,0,0]))
    #print(*i[7]*(intersection_product(M,B,i[:7]+[0,0,0,0,1,0,0])))
    W2CTR+=1
print(W2COLLTOT)
print(W2CTR)

[ 0 -6  0  4  2  2  0  8  4  0]
28


In [92]:
# The codim 3 elts in the basis
# This and the subsequent cells can be ignored.
CODIM3GUYS = np.asarray([
    [0,0,1,0,0,0,0],
    [1,0,0,0,1,0,0],
    [0,1,0,0,1,0,0],
    [1,2,0,0,0,0,0],
    [2,1,0,0,0,0,0],
    [1,0,0,0,0,1,0],
    [1,0,0,0,0,0,1],
    [0,3,0,0,0,0,0],
    [0,1,0,0,0,1,0],
    [0,0,0,1,0,0,0]
])

In [93]:
NEEDSCHECKINGLIST = np.asarray([
    [4,0,0,0,1,0,0],
    [5,1,0,0,0,0,0],
    [4,0,0,0,0,1,0],
    [4,0,0,0,0,0,1],
    [2,0,0,0,2,0,0],
    [3,1,0,0,1,0,0],
    [2,0,0,0,1,1,0],
    [2,0,0,0,1,0,1],
    ######
    [4,2,0,0,0,0,0],
    [3,1,0,0,0,1,0],
    [3,1,0,0,0,0,1],
    [1,1,0,0,2,0,0],
    [2,2,0,0,1,0,0],
    [1,1,0,0,1,1,0],
    [1,1,0,0,1,0,1],
    #####
    [0,0,0,0,3,0,0]
])

In [94]:
BIGCHECK = []
for i in NEEDSCHECKINGLIST:
    for j in CODIM3GUYS:
        BIGCHECK.append(i+j)
#BIGCHECK2 = BIGCHECK.tolist()
BIGCHECK3 = list(set(tuple(sub) for sub in BIGCHECK))
BIGCHECK4 = sorted(BIGCHECK3, key=lambda x: (x[0],x[1]))
BIGCHECK5 = BIGCHECK3.sort()
for i in BIGCHECK4:
    print(i)
len(BIGCHECK3)

(0, 0, 1, 0, 3, 0, 0)
(0, 0, 0, 1, 3, 0, 0)
(0, 1, 0, 0, 4, 0, 0)
(0, 1, 0, 0, 3, 1, 0)
(0, 3, 0, 0, 3, 0, 0)
(1, 0, 0, 0, 3, 0, 1)
(1, 0, 0, 0, 3, 1, 0)
(1, 0, 0, 0, 4, 0, 0)
(1, 1, 0, 1, 2, 0, 0)
(1, 1, 0, 1, 1, 1, 0)
(1, 1, 1, 0, 2, 0, 0)
(1, 1, 1, 0, 1, 0, 1)
(1, 1, 1, 0, 1, 1, 0)
(1, 1, 0, 1, 1, 0, 1)
(1, 2, 0, 0, 2, 0, 1)
(1, 2, 0, 0, 2, 1, 0)
(1, 2, 0, 0, 1, 1, 1)
(1, 2, 0, 0, 1, 2, 0)
(1, 2, 0, 0, 3, 0, 0)
(1, 4, 0, 0, 1, 0, 1)
(1, 4, 0, 0, 1, 1, 0)
(1, 4, 0, 0, 2, 0, 0)
(2, 0, 0, 1, 1, 1, 0)
(2, 0, 0, 1, 1, 0, 1)
(2, 0, 1, 0, 2, 0, 0)
(2, 0, 1, 0, 1, 1, 0)
(2, 0, 1, 0, 1, 0, 1)
(2, 0, 0, 1, 2, 0, 0)
(2, 1, 0, 0, 1, 0, 2)
(2, 1, 0, 0, 2, 1, 0)
(2, 1, 0, 0, 2, 0, 1)
(2, 1, 0, 0, 1, 2, 0)
(2, 1, 0, 0, 3, 0, 0)
(2, 1, 0, 0, 1, 1, 1)
(2, 2, 1, 0, 1, 0, 0)
(2, 2, 0, 1, 1, 0, 0)
(2, 3, 0, 0, 1, 1, 0)
(2, 3, 0, 0, 1, 0, 1)
(2, 3, 0, 0, 2, 0, 0)
(2, 5, 0, 0, 1, 0, 0)
(3, 0, 0, 0, 1, 2, 0)
(3, 0, 0, 0, 1, 1, 1)
(3, 0, 0, 0, 2, 1, 0)
(3, 0, 0, 0, 2, 0, 1)
(3, 0, 0, 0, 1, 0, 2)
(3, 0, 0, 

95

In [95]:
for i in BIGCHECK:
    print(i)

[4 0 1 0 1 0 0]
[5 0 0 0 2 0 0]
[4 1 0 0 2 0 0]
[5 2 0 0 1 0 0]
[6 1 0 0 1 0 0]
[5 0 0 0 1 1 0]
[5 0 0 0 1 0 1]
[4 3 0 0 1 0 0]
[4 1 0 0 1 1 0]
[4 0 0 1 1 0 0]
[5 1 1 0 0 0 0]
[6 1 0 0 1 0 0]
[5 2 0 0 1 0 0]
[6 3 0 0 0 0 0]
[7 2 0 0 0 0 0]
[6 1 0 0 0 1 0]
[6 1 0 0 0 0 1]
[5 4 0 0 0 0 0]
[5 2 0 0 0 1 0]
[5 1 0 1 0 0 0]
[4 0 1 0 0 1 0]
[5 0 0 0 1 1 0]
[4 1 0 0 1 1 0]
[5 2 0 0 0 1 0]
[6 1 0 0 0 1 0]
[5 0 0 0 0 2 0]
[5 0 0 0 0 1 1]
[4 3 0 0 0 1 0]
[4 1 0 0 0 2 0]
[4 0 0 1 0 1 0]
[4 0 1 0 0 0 1]
[5 0 0 0 1 0 1]
[4 1 0 0 1 0 1]
[5 2 0 0 0 0 1]
[6 1 0 0 0 0 1]
[5 0 0 0 0 1 1]
[5 0 0 0 0 0 2]
[4 3 0 0 0 0 1]
[4 1 0 0 0 1 1]
[4 0 0 1 0 0 1]
[2 0 1 0 2 0 0]
[3 0 0 0 3 0 0]
[2 1 0 0 3 0 0]
[3 2 0 0 2 0 0]
[4 1 0 0 2 0 0]
[3 0 0 0 2 1 0]
[3 0 0 0 2 0 1]
[2 3 0 0 2 0 0]
[2 1 0 0 2 1 0]
[2 0 0 1 2 0 0]
[3 1 1 0 1 0 0]
[4 1 0 0 2 0 0]
[3 2 0 0 2 0 0]
[4 3 0 0 1 0 0]
[5 2 0 0 1 0 0]
[4 1 0 0 1 1 0]
[4 1 0 0 1 0 1]
[3 4 0 0 1 0 0]
[3 2 0 0 1 1 0]
[3 1 0 1 1 0 0]
[2 0 1 0 1 1 0]
[3 0 0 0 2 1 0]
[2 1 0 0